apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
stringData:
  accounts.devops.password: "$2y$10$rOdS6vP9Nd3mDU2WidfB/.XgxY8Qcw8zGNmlV3vOOvO1GyxW8vzt."
  accounts.devops.passwordMtime: "2025-12-18T07:30:00Z"

  accounts.backend.password: "$2y$10$tDIUBfkddRreVyg3NYPzVekGptQV.LsnDWD.3iVqMOW1sPJBmKguy"
  accounts.backend.passwordMtime: "2025-12-18T07:30:00Z"
