apiVersion: v1
kind: Pod
metadata:
  name: jenkins-react-agent
  namespace: jenkins
spec:
  serviceAccountName: jenkins-agent
  containers:
  - name: node
    image: node:20
    command: ["cat"]
    tty: true
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "1"
        memory: "2Gi"
