apiVersion: v1
kind: ConfigMap
metadata:
  name: casc-credentials
  namespace: jenkins
data:
  credentials.yaml: |
    credentials:
      system:
        domainCredentials:
          - credentials:
              - string:
                  id: github-token
                  secret: ${GITHUB_TOKEN}
                  description: GitHub access token
