apiVersion: v1
kind: ConfigMap
metadata:
  name: casc-jobs-seed-config
  namespace: jenkins
data:
  casc-jobs-seed.yaml: |
    jobs:
      - script: |
          job('seed-job') {
            description('Seed Job - manage all Jenkins jobs via Job DSL')
    
            scm {
              git {
                remote {
                  url('https://github.com/DanielNugrahaHS/devops-tools.git')
                  credentials('github-token')
                }
                branches('*/main')
              }
            }
    
            steps {
              dsl {
                external('jenkins/job-dsl/jobs/**/*.groovy')
                removeAction('DELETE')
                removeViewAction('DELETE')
                lookupStrategy('JENKINS_ROOT')
              }
            }
          }
