apiVersion: v1
kind: ConfigMap
metadata:
  name: casc-jobdsl-project
  namespace: jenkins
data:
  projects/go.yaml: |
    projects:
      - name: user-service
        port: 8080
        repo: git@github.com:org/user-service.git

  projects/react.yaml: |
    projects:
      - name: admin-ui
        repo: git@github.com:org/admin-ui.git
