apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-init-groovy
  namespace: jenkins
data:
  create-admin.groovy: |
    import jenkins.model.*
    import hudson.security.*

    def instance = Jenkins.getInstance()

    if (!(instance.getSecurityRealm() instanceof HudsonPrivateSecurityRealm)) {
      def realm = new HudsonPrivateSecurityRealm(false)
      instance.setSecurityRealm(realm)
    }

    def realm = instance.getSecurityRealm()

    if (realm.getUser("admin") == null) {
      realm.createAccount("admin", "admin")
      println("✅ admin user created")
    } else {
      println("ℹ️ admin user already exists")
    }

    instance.save()

  01-seed-job.groovy: |
    import jenkins.model.*
    import javaposse.jobdsl.plugin.*
    
    def jenkins = Jenkins.instance
    
    if (jenkins.getItem("seed-job") == null) {
      println "Creating seed-job..."
    
      def job = jenkins.createProject(FreeStyleProject, "seed-job")
    
      job.buildersList.add(new ExecuteDslScripts(
        new ExecuteDslScripts.ScriptLocation(
          ExecuteDslScripts.ScriptLocationType.FILE,
          "jobdsl/seed.groovy",
          null
        ),
        true,
        RemovedJobAction.DELETE,
        RemovedViewAction.DELETE,
        LookupStrategy.JENKINS_ROOT
      ))
    
      job.save()
    } else {
      println "seed-job already exists"
    }


