apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-init-groovy
  namespace: jenkins
data:
  create-admin-and-auto-approve.groovy: |
    import jenkins.model.*
    import hudson.security.*
    import org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval

    def instance = Jenkins.getInstance()

    /*
     * ============================
     * 1. CREATE ADMIN USER
     * ============================
     */
    if (!(instance.getSecurityRealm() instanceof HudsonPrivateSecurityRealm)) {
      def realm = new HudsonPrivateSecurityRealm(false)
      instance.setSecurityRealm(realm)
    }

    def realm = instance.getSecurityRealm()

    if (realm.getUser("admin") == null) {
      realm.createAccount("admin", "admin")
      println("✅ admin user created")
    } else {
      println("ℹ️ admin user already exists")
    }

    /*
     * ============================
     * 2. AUTO APPROVE SCRIPT SECURITY
     * ============================
     */
    println("Auto-approving all Groovy scripts (Script Security)")
    try {
      ScriptApproval.get().preapproveAll()
      println("All scripts pre-approved")
    } catch (Exception e) {
      println("Failed to auto-approve scripts: ${e.message}")
    }

    instance.save()

  disable-jobdsl-security.groovy: |
    import javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration
    import jenkins.model.GlobalConfiguration

    def config = GlobalConfiguration.all().get(GlobalJobDslSecurityConfiguration.class)
    config.useScriptSecurity = false
    config.save()

  auto-approve-jobdsl.groovy: |
    import org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval

    def scriptApproval = ScriptApproval.get()
    scriptApproval.pendingScripts.each { pending ->
        scriptApproval.approveScript(pending.getHash())
    }