apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-init-groovy
  namespace: jenkins
data:
  create-admin-and-auto-approve.groovy: |
    import jenkins.model.*
    import hudson.security.*
    import org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval

    def instance = Jenkins.getInstance()

    /*
     * ============================
     * 1. CREATE ADMIN USER
     * ============================
     */
    if (!(instance.getSecurityRealm() instanceof HudsonPrivateSecurityRealm)) {
      def realm = new HudsonPrivateSecurityRealm(false)
      instance.setSecurityRealm(realm)
    }

    def realm = instance.getSecurityRealm()

    if (realm.getUser("admin") == null) {
      realm.createAccount("admin", "admin")
      println("✅ admin user created")
    } else {
      println("ℹ️ admin user already exists")
    }

    /*
     * ============================
     * 2. AUTO APPROVE ALL SCRIPTS
     * ============================
     */
    try {
      println("Auto-approving all Groovy scripts (Script Security)")
      ScriptApproval.get().preapproveAll()
      println("All scripts approved")
    } catch (Exception e) {
      println("❌ Failed to auto-approve scripts: ${e.message}")
    }

    instance.save()